// Generated by gencpp from file lio_sam_6axis/save_mapRequest.msg
// DO NOT EDIT!


#ifndef LIO_SAM_6AXIS_MESSAGE_SAVE_MAPREQUEST_H
#define LIO_SAM_6AXIS_MESSAGE_SAVE_MAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lio_sam_6axis
{
template <class ContainerAllocator>
struct save_mapRequest_
{
  typedef save_mapRequest_<ContainerAllocator> Type;

  save_mapRequest_()
    {
    }
  save_mapRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::lio_sam_6axis::save_mapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lio_sam_6axis::save_mapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct save_mapRequest_

typedef ::lio_sam_6axis::save_mapRequest_<std::allocator<void> > save_mapRequest;

typedef boost::shared_ptr< ::lio_sam_6axis::save_mapRequest > save_mapRequestPtr;
typedef boost::shared_ptr< ::lio_sam_6axis::save_mapRequest const> save_mapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lio_sam_6axis::save_mapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lio_sam_6axis::save_mapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace lio_sam_6axis

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lio_sam_6axis::save_mapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lio_sam_6axis::save_mapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lio_sam_6axis::save_mapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lio_sam_6axis::save_mapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lio_sam_6axis::save_mapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lio_sam_6axis::save_mapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lio_sam_6axis::save_mapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::lio_sam_6axis::save_mapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::lio_sam_6axis::save_mapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lio_sam_6axis/save_mapRequest";
  }

  static const char* value(const ::lio_sam_6axis::save_mapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lio_sam_6axis::save_mapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#string destination\n"
"#float32 resolution\n"
"#string name\n"
;
  }

  static const char* value(const ::lio_sam_6axis::save_mapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lio_sam_6axis::save_mapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct save_mapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lio_sam_6axis::save_mapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::lio_sam_6axis::save_mapRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LIO_SAM_6AXIS_MESSAGE_SAVE_MAPREQUEST_H
